{{- if .Values.developer.enabled  }}
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-cs-store
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-3"
    "helm.sh/resource-policy": keep
    #pv.beta.kubernetes.io/gid: "1234"
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 2Gi
  hostPath:
    path: /cs_store
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-cs-store
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-3"
    "helm.sh/resource-policy": keep
spec:
  storageClassName: ""
  {{ if .Values.developer.enabled  }}
  volumeName: pv-cs-store
  {{ end }}
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
{{- end }}
